version: "3"
networks:
  default:
services:
  frontend:
    image: openresty/openresty:latest
    container_name: frontend
    # bugfix
    command: "ln -s /usr/local/openresty/lualib/resty /usr/local/openresty/nginx/conf/waf/resty && /usr/bin/openresty -g daemon off;"
    networks:
      - default
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/localtime:/etc/localtime
      - /nginx/nginx.conf:/usr/local/openresty/nginx/conf/nginx.conf  # nginx配置文件
      - /nginx/ssl:/usr/local/openresty/nginx/ssl                     # nginx证书
      - /nginx/waf:/usr/local/openresty/nginx/conf/waf                # waf的lua脚本
    restart: always
  backend:
    image: crm:latest
    container_name: backend
    networks:
      - default
    depends_on:
      - redis
      - mysql
    expose:
      - "8080"
    volumes:
      - /etc/localtime:/etc/localtime
      - /app/logs:/usr/local/crm/app/logs     # 后端服务的日志
      - /app/upload:/usr/local/crm/app/files  # 后端服务的上传文件
      - /app/download:/usr/local/crm/app/temp # 后端服务的下载文件
    restart: always
  redis:
    image: redis:latest
    container_name: redis
    command: "redis-server /etc/redis/redis.conf"
    networks:
      - default
    expose:
      - "6379"
    volumes:
      - /etc/localtime:/etc/localtime
      - /redis/redis.conf:/etc/redis/redis.conf  # redis配置文件
      - /redis/data:/data                        # redis的快照、数据备份目录
    restart: always
  mysql:
    image: mysql:latest
    container_name: mysql
    environment:
      - MYSQL_ROOT_PASSWORD: "YH56qw#M"  # mysql的密码
      - MYSQLD_EVENT_SCHEDULER: "ON"     # 是否开启计划任务
      - MYSQL_SQL_MODE: "STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION" # 设置group_by
    networks:
      - default
    expose:
      - "3306"
    volumes:
      - /etc/localtime:/etc/localtime
      # - /mysql/my.cnf:/etc/my.cnf                             # mysql的配置文件
      - /mysql/init.sql:/docker-entrypoint-initdb.d/init.sql  # 将初始化sql挂载在此目录
      - /mysql/data:/var/lib/mysql                            # mysql的数据目录
    restart: always     
  clamav:
    image: clamav:clamav:1.2_base
    container_name: clamav
    networks:
      - default
    expose:
      - "3310"
    volumes:
      - /etc/localtime:/etc/localtime
      - /clamav/data:/var/lib/clamav  # 病毒库挂载
    deploy:
      resources:
        limits:
          memory: 1000M
    restart: always      
